name: Update Docker Deployment

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to deploy (default 'latest')"
        required: false
        default: latest
      
jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH to Server and Update Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASPBERRY_SSH_HOST }}
          username: ${{ secrets.RASPBERRY_SSH_USER }}
          key: ${{ secrets.RASPBERRY_SSH_PRIVATE_KEY }}
          script: |
            cd ApkiPawla/empeka
            docker compose pull
            docker image prune -f
